export default {
  state() {
    return {
      tasks: [
        {
          id: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
          name: 'Task 1',
          date: '2022-07-15',
          server: 5,
          application: 2,
          serverId: 'EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIj',
          applicationId: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
        },
        {
          id: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
          name: 'Task 2',
          date: '2021-11-23',
          server: 1,
          application: 2,
          serverId: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
          applicationId: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
        },
        {
          id: 'CdEfGhIjKlMnOpQrStUvWxYzAbCdEfGh',
          name: 'Task 3',
          date: '2020-04-10',
          server: 2,
          application: 3,
          serverId: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
          applicationId: 'CdEfGhIjKlMnOpQrStUvWxYzAbCdEfGh',
        },
        {
          id: 'DeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHi',
          name: 'Task 4',
          date: '2023-08-19',
          server: 2,
          application: 10,
          serverId: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
          applicationId: 'JkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNo',
        },
        {
          id: 'EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIj',
          name: 'Task 5',
          date: '2021-01-05',
          server: 5,
          application: 5,
          serverId: 'EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIj',
          applicationId: 'EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIj',
        },
        {
          id: 'FgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJk',
          name: 'Task 6',
          date: '2020-06-15',
          server: 2,
          application: 9,
          serverId: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
          applicationId: 'FgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJk',
        },
        {
          id: 'GhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
          name: 'Task 7',
          date: '2023-02-28',
          server: 1,
          application: 11,
          serverId: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
          applicationId: 'JkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNo',
        },
        {
          id: 'HiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLm',
          name: 'Task 8',
          date: '2022-03-19',
          server: 4,
          application: 7,
          serverId: 'DeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHi',
          applicationId: 'HiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLm',
        },
        {
          id: 'IjKlMnOpQrStUvWxYzAbCdEfGhIjKlMn',
          name: 'Task 9',
          date: '2021-10-20',
          server: 4,
          application: 11,
          serverId: 'DeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHi',
          applicationId: 'JkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNo',
        },
        {
          id: 'JkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNo',
          name: 'Task 10',
          date: '2020-09-12',
          server: 2,
          application: 0,
          serverId: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
          applicationId: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
        },
        {
          id: 'KlMnOpQrStUvWxYzAbCdEfGhIjKlMnOp',
          name: 'Task 11',
          date: '2023-04-01',
          server: 2,
          application: 1,
          serverId: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
          applicationId: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
        },
        {
          id: 'LmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPq',
          name: 'Task 12',
          date: '2022-05-30',
          server: 1,
          application: 11,
          serverId: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
          applicationId: 'JkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNo',
        },
        {
          id: 'MnOpQrStUvWxYzAbCdEfGhIjKlMnOpQr',
          name: 'Task 13',
          date: '2021-03-22',
          server: 4,
          application: 0,
          serverId: 'DeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHi',
          applicationId: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
        },
        {
          id: 'NoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRs',
          name: 'Task 14',
          date: '2020-11-13',
          server: 4,
          application: 5,
          serverId: 'DeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHi',
          applicationId: 'EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIj',
        },
        {
          id: 'OpQrStUvWxYzAbCdEfGhIjKlMnOpQrSt',
          name: 'Task 15',
          date: '2023-07-25',
          server: 2,
          application: 3,
          serverId: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
          applicationId: 'CdEfGhIjKlMnOpQrStUvWxYzAbCdEfGh',
        },
        {
          id: 'PqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTu',
          name: 'Task 16',
          date: '2022-12-18',
          server: 5,
          application: 1,
          serverId: 'EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIj',
          applicationId: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
        },
        {
          id: 'QrStUvWxYzAbCdEfGhIjKlMnOpQrStUv',
          name: 'Task 17',
          date: '2022-09-06',
          server: 4,
          application: 4,
          serverId: 'DeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHi',
          applicationId: 'CdEfGhIjKlMnOpQrStUvWxYzAbCdEfGh',
        },
        {
          id: 'RsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVw',
          name: 'Task 18',
          date: '2021-08-27',
          server: 5,
          application: 2,
          serverId: 'EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIj',
          applicationId: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
        },
        {
          id: 'TuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXy',
          name: 'Task 19',
          date: '2022-02-14',
          server: 1,
          application: 4,
          serverId: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
          applicationId: 'CdEfGhIjKlMnOpQrStUvWxYzAbCdEfGh',
        },
        {
          id: 'UvWxYzAbCdEfGhIjKlMnOpQrStUvWxYz',
          name: 'Task 20',
          date: '2020-12-02',
          server: 1,
          application: 9,
          serverId: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
          applicationId: 'FgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJk',
        },
        {
          id: 'VwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZa',
          name: 'Task 21',
          date: '2022-01-28',
          server: 3,
          application: 3,
          serverId: 'CdEfGhIjKlMnOpQrStUvWxYzAbCdEfGh',
          applicationId: 'CdEfGhIjKlMnOpQrStUvWxYzAbCdEfGh',
        },
        {
          id: 'WxYzAbCdEfGhIjKlMnOpQrStUvWxYzAb',
          name: 'Task 22',
          date: '2023-05-17',
          server: 5,
          application: 6,
          serverId: 'EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIj',
          applicationId: 'IjKlMnOpQrStUvWxYzAbCdEfGhIjKlMn',
        },
        {
          id: 'XyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBc',
          name: 'Task 23',
          date: '2021-07-09',
          server: 3,
          application: 4,
          serverId: 'CdEfGhIjKlMnOpQrStUvWxYzAbCdEfGh',
          applicationId: 'CdEfGhIjKlMnOpQrStUvWxYzAbCdEfGh',
        },
        {
          id: 'YzAbCdEfGhIjKlMnOpQrStUvWxYzAbCd',
          name: 'Task 24',
          date: '2020-02-04',
          server: 1,
          application: 5,
          serverId: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
          applicationId: 'EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIj',
        },
        {
          id: 'ZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
          name: 'Task 25',
          date: '2022-10-11',
          server: 4,
          application: 7,
          serverId: 'DeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHi',
          applicationId: 'HiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLm',
        },
        {
          id: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
          name: 'Task 26',
          date: '2022-04-06',
          server: 5,
          application: 0,
          serverId: 'EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIj',
          applicationId: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
        },
        {
          id: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgH',
          name: 'Task 27',
          date: '2021-01-30',
          server: 2,
          application: 8,
          serverId: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
          applicationId: 'GhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
        },
        {
          id: 'CdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhI',
          name: 'Task 28',
          date: '2020-08-21',
          server: 3,
          application: 6,
          serverId: 'CdEfGhIjKlMnOpQrStUvWxYzAbCdEfGh',
          applicationId: 'IjKlMnOpQrStUvWxYzAbCdEfGhIjKlMn',
        },
        {
          id: 'DeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJ',
          name: 'Task 29',
          date: '2023-01-09',
          server: 1,
          application: 1,
          serverId: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
          applicationId: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
        },
        {
          id: 'EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjK',
          name: 'Task 30',
          date: '2020-03-25',
          server: 5,
          application: 7,
          serverId: 'EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIj',
          applicationId: 'HiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLm',
        },
      ],
    };
  },
  getters: {
    getTasks(state) {
      return state.tasks;
    },
  },
};
