export default {
  state() {
    return {
      items: [
        {
          id: 'aBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
          name: 'Task 1',
          date: '2022-07-15',
          server: 5,
          application: 2,
        },
        {
          id: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
          name: 'Task 2',
          date: '2021-11-23',
          server: 1,
          application: 2,
        },
        {
          id: 'CdEfGhIjKlMnOpQrStUvWxYzAbCdEfGh',
          name: 'Task 3',
          date: '2020-04-10',
          server: 2,
          application: 3,
        },
        {
          id: 'DeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHi',
          name: 'Task 4',
          date: '2023-08-19',
          server: 2,
          application: 10,
        },
        {
          id: 'EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIj',
          name: 'Task 5',
          date: '2021-01-05',
          server: 5,
          application: 5,
        },
        {
          id: 'FgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJk',
          name: 'Task 6',
          date: '2020-06-15',
          server: 2,
          application: 9,
        },
        {
          id: 'GhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
          name: 'Task 7',
          date: '2023-02-28',
          server: 1,
          application: 11,
        },
        {
          id: 'HiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLm',
          name: 'Task 8',
          date: '2022-03-19',
          server: 4,
          application: 7,
        },
        {
          id: 'IjKlMnOpQrStUvWxYzAbCdEfGhIjKlMn',
          name: 'Task 9',
          date: '2021-10-20',
          server: 4,
          application: 11,
        },
        {
          id: 'JkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNo',
          name: 'Task 10',
          date: '2020-09-12',
          server: 2,
          application: 0,
        },
        {
          id: 'KlMnOpQrStUvWxYzAbCdEfGhIjKlMnOp',
          name: 'Task 11',
          date: '2023-04-01',
          server: 2,
          application: 1,
        },
        {
          id: 'LmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPq',
          name: 'Task 12',
          date: '2022-05-30',
          server: 1,
          application: 11,
        },
        {
          id: 'MnOpQrStUvWxYzAbCdEfGhIjKlMnOpQr',
          name: 'Task 13',
          date: '2021-03-22',
          server: 4,
          application: 0,
        },
        {
          id: 'NoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRs',
          name: 'Task 14',
          date: '2020-11-13',
          server: 4,
          application: 5,
        },
        {
          id: 'OpQrStUvWxYzAbCdEfGhIjKlMnOpQrSt',
          name: 'Task 15',
          date: '2023-07-25',
          server: 2,
          application: 3,
        },
        {
          id: 'PqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTu',
          name: 'Task 16',
          date: '2022-12-18',
          server: 5,
          application: 10,
        },
        {
          id: 'QrStUvWxYzAbCdEfGhIjKlMnOpQrStUv',
          name: 'Task 17',
          date: '2021-06-14',
          server: 1,
          application: 0,
        },
        {
          id: 'RsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVw',
          name: 'Task 18',
          date: '2020-08-21',
          server: 2,
          application: 5,
        },
        {
          id: 'StUvWxYzAbCdEfGhIjKlMnOpQrStUvWx',
          name: 'Task 19',
          date: '2023-05-12',
          server: 4,
          application: 7,
        },
        {
          id: 'TuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXy',
          name: 'Task 20',
          date: '2022-01-27',
          server: 2,
          application: 10,
        },
        {
          id: 'UvWxYzAbCdEfGhIjKlMnOpQrStUvWxYz',
          name: 'Task 21',
          date: '2021-09-03',
          server: 5,
          application: 11,
        },
        {
          id: 'VwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZa',
          name: 'Task 22',
          date: '2020-10-28',
          server: 1,
          application: 5,
        },
        {
          id: 'WxYzAbCdEfGhIjKlMnOpQrStUvWxYzAb',
          name: 'Task 23',
          date: '2023-02-06',
          server: 3,
          application: 2,
        },
        {
          id: 'XyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBc',
          name: 'Task 24',
          date: '2022-11-29',
          server: 4,
          application: 5,
        },
        {
          id: 'YzAbCdEfGhIjKlMnOpQrStUvWxYzAbCd',
          name: 'Task 25',
          date: '2021-12-01',
          server: 2,
          application: 8,
        },
        {
          id: 'ZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDe',
          name: 'Task 26',
          date: '2020-05-14',
          server: 4,
          application: 3,
        },
        {
          id: 'AbCdEfGhIjKlMnOpQrStUvWxYzAbCdEf',
          name: 'Task 27',
          date: '2023-03-10',
          server: 1,
          application: 4,
        },
        {
          id: 'BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFg',
          name: 'Task 28',
          date: '2022-09-23',
          server: 3,
          application: 5,
        },
        {
          id: 'CdEfGhIjKlMnOpQrStUvWxYzAbCdEfGh',
          name: 'Task 29',
          date: '2021-04-09',
          server: 4,
          application: 8,
        },
        {
          id: 'DeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHi',
          name: 'Task 30',
          date: '2020-07-11',
          server: 1,
          application: 11,
        },
      ],
    };
  },
  getters: {
    getTasks(state) {
      return state.items;
    },
  },
};
